var attendants = [
    "Phyo Min Thu",
    "May Pearl Aung",
    "Ying Wit Mon Win",
    "Soe Thiha",
    "Saw Charles",
    "Phway Thant Chae",
    "Ye' Linn Wai",
    "Aung Ko Ko",
    "Nyan Lin Tun",
    "Saw Le Ya Gaw",
    "Myo Zaw Oo",
    "Paing Soe Aung",
    "Naw Say Say Shee",
    "Hein Htet Aung",
    "Hnin Myat Phyu",
    "Kyaw Naing Tun",
    "Thiha Tun",
    "Wyne Phyu Cin",
    "Thar Htet",
    "Khin Myo Hsae",
    "Win Htaik Aung",
    "Hay Mann Moe",
    "Pyi Thein Khine",
    "zanzan",
    "Aung Pyae Phyo",
    "Ye Kyaw Thu",
    "Phyu Thinn Aung",
    "Aye Mon Kyaw",
    "kyawminlwin",
    "Than Soe Han",
    "Aung Pyae Sone",
    "Kay Kay Khine",
    "Thaw Lwin Htun",
    "Nyi Nyi Phyo",
    "Kyaw San Win",
    "Hnin Lwin Lwin",
    "Shwe Yee Winn",
    "Ohnmar Soe",
    "Thura Lwin",
    "Poe Ei Phyu",
    "Kyaw Zin Htike",
    "Aung Thu Kyaw",
    "Nyan Lin Zaw",
    "Win Mar Thant",
    "THURA",
    "Thazin Nwe",
    "Htet Wai Phyo"
];

var TOTAL_WINNERS = 10;
var PLAY_TIME = 3000;
var LOOP = 2;
